apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: uberapp-deployment
spec:
  replicas: 4 
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: uberapp
    spec:
      containers:
      - name: uberapp
        image: jocatalin/uberapp:v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: uberapp-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: uberapp
  type: NodePort